services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=db_book_store'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5434:5432'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always