services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=db_book_store'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5434:5432'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - 'KAFKA_ENABLE_KRAFT=yes'
      - 'KAFKA_CFG_NODE_ID=1'
      - 'KAFKA_CFG_PROCESS_ROLES=broker,controller'
      - 'KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093'
      - 'KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER'
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,DOCKER://:29092,CONTROLLER://:9093'
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,DOCKER://kafka:29092'
      - 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT'
      - 'KAFKA_KRAFT_CLUSTER_ID=kraft-cluster'
    ports:
      - "9092:9092"
      - "29092:29092"


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - 'KAFKA_CLUSTERS_0_NAME=local'
      - 'KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092'
    depends_on:
      - kafka

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - /c/Users/user/Desktop/projects/book/logs:/usr/share/logstash/logs
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    user: root
    volumes:
      - /c/Users/user/Desktop/projects/book/logs:/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    entrypoint: [ "/bin/sh", "-c", "chmod 644 /usr/share/filebeat/filebeat.yml && filebeat -e" ]
    depends_on:
      - logstash