services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=db_book_store'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5434:5432'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - 'KAFKA_ENABLE_KRAFT=yes'
      - 'KAFKA_CFG_NODE_ID=1'
      - 'KAFKA_CFG_PROCESS_ROLES=broker,controller'
      - 'KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093'
      - 'KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER'
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093'
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092'
      - 'KAFKA_KRAFT_CLUSTER_ID=kraft-cluster'
    ports:
      - "9092:9092"