spring:
  application:
    name: book

  messages:
    basename: messages_validations
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5434/db_book_store
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379

  config:
    import: optional:classpath:application-secrets.yaml

logging:
  level:
    org:
      springframework:
        security: DEBUG